(function(){
  const policies={
    privacy:{title:'Privacy Policy',body:`<p>Muntaha Mall respects your privacy. We collect only the information needed to provide accounts, orders, delivery, customer support, fraud prevention and payment processing.</p><p>Payment card and sensitive payment details are handled by the selected payment provider. Muntaha Mall does not intentionally store full card numbers or CVV data.</p><p>We may use cookies and similar technologies for login sessions, cart functionality, preferences and site security. You may contact us to request help regarding your personal information.</p>`},
    refund:{title:'Return & Refund Policy',body:`<p>Customers may request a return or refund according to the product category, seller terms and applicable Pakistani consumer requirements.</p><p>Items should be unused and returned in suitable original condition where applicable. Some hygiene, personalized or perishable products may be non-returnable except where required by law.</p><p>Approved refunds are processed after the return is received and checked. For online payments, refunds are sent through the applicable payment method/provider where supported.</p>`},
    shipping:{title:'Shipping / Service Policy',body:`<p>Muntaha Mall delivers products through available courier and logistics partners in Pakistan. Delivery time and charges can vary by seller, product, destination and courier service.</p><p>Customers receive order/delivery updates through the contact details supplied at checkout. Delays caused by weather, courier operations, holidays or circumstances outside our reasonable control may occur.</p>`},
    terms:{title:'Terms & Conditions',body:`<p>By using Muntaha Mall, you agree to use the website lawfully and provide accurate account and delivery information.</p><p>Product prices, stock, descriptions and seller information may change. An order becomes subject to confirmation and availability. Fraudulent, abusive or unauthorized activity may result in order cancellation or account restriction.</p><p>Marketplace products may be supplied by independent sellers. Muntaha Mall may facilitate the transaction, payment and customer support in accordance with the applicable seller and marketplace terms.</p>`},
    contact:{title:'Contact Us',body:`<div class="contact-card"><p><strong>Business:</strong> Muntaha Mall</p><p><strong>Business Address:</strong> <span class="needs-update">Please add your real local office/business address before PayFast verification.</span></p><p><strong>Phone:</strong> <span class="needs-update">Please add your real business contact number before PayFast verification.</span></p><p><strong>Email:</strong> <span class="needs-update">Please add your real support email before PayFast verification.</span></p><p><strong>Support:</strong> Customer support for orders, returns, shipping and payment issues.</p></div><div class="compliance-note"><strong>Merchant verification checklist:</strong> Keep the business address, contact number and support email visible and accurate on this page before submitting the website for payment-gateway verification.</div>`}
  };
  function openPolicy(key){
    const p=policies[key]; if(!p) return;
    let m=document.getElementById('mmLegalModal');
    if(!m){m=document.createElement('div');m.id='mmLegalModal';m.className='mm-legal-modal';m.innerHTML='<div class="mm-legal-backdrop"></div><div class="mm-legal-dialog"><button class="mm-legal-close" aria-label="Close">×</button><h2></h2><div class="mm-legal-content"></div></div>';document.body.appendChild(m);m.querySelector('.mm-legal-backdrop').onclick=()=>m.remove();m.querySelector('.mm-legal-close').onclick=()=>m.remove();}
    m.querySelector('h2').textContent=p.title;m.querySelector('.mm-legal-content').innerHTML=p.body;m.style.display='flex';
  }
  document.addEventListener('click',e=>{const a=e.target.closest('[data-legal]');if(a){e.preventDefault();openPolicy(a.dataset.legal);}});
})();
